### ISSUE TITLE
State var change callback

### ISSUE THREAD

**Issue by madeInLagny** [gitaarik/lit-state#10]
Hello,
Thank you for your great work with lit-state. I am trying to catch a state var change call back to trigger some actions when a specific state var gets updated.
```
updated(changedProperties) {
  if (changedProperties.has('myState.collapsed')) {
doSomething()
  }
}
```
won't work because myState.collapsed is not a component property.
What is the recommended method to catch that state var update callback ?

**Comment by christophe-g** [comment]
I would add an observer on connectedCallback in this case: 

```js
connectedCallback() {
  super.connectedCallback()
  myState.addObserver(() => {dothings}, ['collapsed'])
}
 
```

and remove the observer at disconnectedCallback

**Comment by madeInLagny** [comment]
Will do so. Thanks

**Comment by gitaarik** [comment]
That's the way indeed. Also [documented here](https://gitaarik.github.io/lit-state/build/#advanced-usage/manually-observe-state/).
