### ISSUE TITLE
Can I fork this project and rewrite it to support TS version?

### ISSUE THREAD

**Issue by xxxsf** [gitaarik/lit-state#12]
Can I fork this project and rewrite it to support TS version?

**Comment by xxxsf** [comment]
long time no reply, so I close it now. thx

**Comment by gitaarik** [comment]
Hey @xsf0105. Sure you can fork it. Maybe if it works out, we could merge it back into this project?

**Comment by xxxsf** [comment]
Hi, @gitaarik. Glad to have finally waited for your reply. Sure~
And why you set it with LGPL instead of MIT?

**Comment by xsf0105** [comment]
By the way, your avatar is cool, I like it ~

 : )

**Comment by gitaarik** [comment]
Because LGPL is a copy-left licence that preserves the software's freedom. The MIT license permits people to fork the software and make it proprietary, which I don't want.
